apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:krafty1010/k8s.git
    path: appofapps/applications
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc  
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  